version: '3'
services:
    nginx1:
        restart: always
        container_name: nginx1
        image: nginx
        platform: linux
        user: root
        ports:
            - "8083:80"
        volumes:
            - ./web1:/usr/share/nginx/html
        networks:
            - default
    
    nginx2:
        restart: always
        container_name: nginx2
        image: nginx
        platform: linux
        user: root
        ports:
            - "8084:80"
        volumes:
            - ./web2:/usr/share/nginx/html
        networks:
            - default

    ##nginx8093:latest is imported image, just a filesytem image
    #nginx3:
    #    restart: always
    #    container_name: nginx3
    #    image: nginx8093:latest
    #    user: root
    #    stdin_open: true # docker run -i
    #    tty: true        # docker run -t
    #    entrypoint: /bin/sh /docker-entrypoint.sh nginx -g 'daemon off;'
    #    ports:
    #        - "8093:8093"
    #    volumes:
    #        - ./web3:/usr/share/nginx/html
    #    #command:
    #    #    - "/docker-entrypoint.sh nginx"
    #    #     - "/bin/sh -c /docker-entrypoint.sh nginx"
    #    networks:
    #        - default

    #porxy:
    #    restart: always
    #    container_name: proxy
    #    image: nginx
    #    user: root
    #    ports:
    #        - "80:80"
    #    volumes:
    #        - ./proxy:/usr/share/nginx/html
    #        - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    #    networks:
    #    #    - default
    #    #    - my_network
    #        my_static_network:
    #            ipv4_address: 172.20.0.2

    etcd:
        restart: always
        container_name: etcd
        image: quay.io/coreos/etcd:v3.4.14
        platform: linux
        user: root
        entrypoint: /usr/local/bin/etcd
        ports:
            - "2379:2379"
            - "2380:2380"
        volumes:
            - ./etcd/data:/var/lib/etcd
        command:
            - "--name=etcd_node1"
            - "--listen-client-urls=http://0.0.0.0:2379"
            - "--advertise-client-urls=http://0.0.0.0:2379"
            - "--data-dir=/var/lib/etcd"
        networks:
            - default

    #confd:
    #    restart: always
    #    container_name: confd
    #    image: dockage/confd
    #    user: root
    #    #ports:
    #    volumes:
    #        - ./confd/confd:/etc/confd/conf.d
    #        - ./confd/templates:/etc/confd/templates
    #        - ./proxy/default.conf:/tmp/default.conf
    #    networks:
    #    #    - my_network
    #        my_static_network:
    #            ipv4_address: 172.20.0.4

    cadvisor:
        restart: always
        container_name: cadvisor
        image: google/cadvisor
        platform: linux
        user: root
        ports:
            - "8080:8080"
        #volumes:
            #- /:/rootfs:ro
            #- /var/run:/var/run:rw
            #- /sys:/sys:ro
            #- /var/lib/docker/:/var/lib/docker:ro
            #- /dev/disk/:/dev/disk:ro
        networks:
            - default
        depends_on:
            - etcd
            - nginx1
            - nginx2
