# This playbook create Dynamic Reverse Proxy
- name: Create Dynamic Reverse Proxy

  vars:
   urlrewrite_filename: rewrite_amd64_zh-TW.msi
   ARR_filename: requestRouter_amd64.msi
   etcd_filename: etcd-v3.4.14-windows-amd64.zip
   confd_filename: confd-0.16.0-windows-amd64.exe
   winexporter_filename: windows_exporter-0.16.0-amd64.exe
   boxexporter_filename: blackbox_exporter-0.19.0.windows-amd64.zip
   nssm_filename: nssm-2.24.zip
   etcd_src_folder: etcd-v3.4.14-windows-amd64
   etcd_dst_folder: etcd
   etcd_exe: etcd.exe
   confd_exe: confd.exe
   winexporter_exe: windows_exporter.exe
   boxexporter_src_folder: blackbox_exporter-0.19.0.windows-amd64
   boxexporter_dst_folder: blackbox_exporter
   boxexporter_exe: blackbox_exporter.exe
   etcd_bat: etcd.bat
   confd_bat: confd.bat
   exporter_bat: exporter.bat

  hosts: "{{myhost}}"
  gather_facts: false    

  tasks:
   - name: Debug
     debug:
       msg: "{{urlrewrite_filename}}"

   - name: Host Ping Check
     ignore_errors: yes
     win_ping:
     register: var_ping

   - name: Get Host name
     debug: msg="{{var_ping}}"

   #Stop processes
   - name: Stop process (blackbox_exporter)
     win_command: powershell.exe -
     args:
       stdin: Stop-Process -name blackbox_exporter
     ignore_errors: yes

   - name: Stop process (windows_exporter)
     win_command: powershell.exe -
     args:
       stdin: Stop-Process -name windows_exporter
     ignore_errors: yes

   - name: Stop process (confd)
     win_command: powershell.exe -
     args:
       stdin: Stop-Process -name confd
     ignore_errors: yes

   - name: Stop process (etcd)
     win_command: powershell.exe -
     args:
       stdin: Stop-Process -name etcd
     ignore_errors: yes
       
   - name: Create saving folder
     win_file:
       path: D:\reverseproxy
       state: directory

   - name: Remove directory structure
     win_file:
       path: "D:\\reverseproxy\\install"
       state: absent

   - name: Create install folder
     win_file:
       path: D:\reverseproxy\install
       state: directory

   - name: Remove directory structure
     win_file:
       path: "D:\\reverseproxy\\execute"
       state: absent

   - name: Create execute folder
     win_file:
       path: D:\reverseproxy\execute
       state: directory

   #use copy to replace download
   - name: Copy file (urlwrite)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{urlrewrite_filename}}"
       dest: D:\reverseproxy\install\

   - name: Copy file (ARR)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{ARR_filename}}"
       dest: D:\reverseproxy\install\

   - name: Copy file (etcd)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{etcd_filename}}"
       dest: D:\reverseproxy\install\

   - name: Copy file (confd)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{confd_filename}}"
       dest: D:\reverseproxy\install\

   - name: Copy file (windows_exporter)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{winexporter_filename}}"
       dest: D:\reverseproxy\install\

   - name: Copy file (blackbox_exporter)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{boxexporter_filename}}"
       dest: D:\reverseproxy\install\

   #Copy script for execute program
   - name: Copy file (etcd bat)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{etcd_bat}}"
       dest: D:\reverseproxy\execute\

   - name: Copy file (confd bat)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{confd_bat}}"
       dest: D:\reverseproxy\execute\

   - name: Copy file (exporter bat)
     win_copy:
       src: "/home/dino/Desktop/VMShared/Ansible/reverseproxy/{{exporter_bat}}"
       dest: D:\reverseproxy\execute\

   - name: Unzip file (etcd)
     win_command: powershell.exe -
     args:
       stdin: C:\'Program Files'\7-Zip\7z.exe x -y "D:\reverseproxy\install\{{etcd_filename}}" "-oD:\reverseproxy\execute\"

   - name: Remove directory structure
     win_file:
       path: "D:\\reverseproxy\\execute\\{{ etcd_dst_folder }}"
       state: absent

   - name: Change folder name (etcd)
     win_command: "cmd.exe /c rename D:\\reverseproxy\\execute\\{{etcd_src_folder}} {{ etcd_dst_folder }}"

   - name: Create etcd data folder
     win_file:
       path: "D:\\reverseproxy\\execute\\{{ etcd_dst_folder }}\\data"
       state: directory

   - name: Unzip file (blackbox_exporter)
     win_command: powershell.exe -
     args:
       stdin: C:\'Program Files'\7-Zip\7z.exe x -y "D:\reverseproxy\install\{{boxexporter_filename}}" "-oD:\reverseproxy\execute\"

   - name: Remove directory structure
     win_file:
       path: "D:\\reverseproxy\\execute\\{{ boxexporter_dst_folder }}"
       state: absent

   - name: Change folder name (blackbox_exporter)
     win_command: "cmd.exe /c rename D:\\reverseproxy\\execute\\{{boxexporter_src_folder}} {{ boxexporter_dst_folder }}"
    
   - name: install file (urlrewrite)
     win_package:
       path: D:\reverseproxy\install\rewrite_amd64_zh-TW.msi
       state: present

   - name: install file (ARR)
     win_package:
       path: D:\reverseproxy\install\requestRouter_amd64.msi
       state: present

   - name: Create confd folder
     win_file:
       path: D:\reverseproxy\execute\confd
       state: directory

   - name: Create confd\conf.d folder
     win_file:
       path: D:\reverseproxy\execute\confd\conf.d
       state: directory

   - name: Create confd\templates folder
     win_file:
       path: D:\reverseproxy\execute\confd\templates
       state: directory

   - name: Copy file (confd proxy.toml)
     win_copy:
       src: /home/dino/Desktop/VMShared/Ansible/reverseproxy/confd/conf.d/proxy.toml
       dest: D:\reverseproxy\execute\confd\conf.d\

   - name: Copy file (confd proxy.conf.tmpl)
     win_copy:
       src: /home/dino/Desktop/VMShared/Ansible/reverseproxy/confd/templates/proxy.conf.tmpl
       dest: D:\reverseproxy\execute\confd\templates\

   - name: Set file (confd.exe)
     win_copy:
       src: "D:\\reverseproxy\\install\\{{confd_filename}}"
       dest: "D:\\reverseproxy\\execute\\{{confd_exe}}"
       remote_src: yes

   - name: Set file (winexporter.exe)
     win_copy:
       src: "D:\\reverseproxy\\install\\{{winexporter_filename}}"
       dest: "D:\\reverseproxy\\execute\\{{winexporter_exe}}"
       remote_src: yes

   #Enable IIS ARR
   - name: Enable IIS ARR
     win_command: powershell.exe -
     args:
       stdin: Set-WebConfigurationProperty -filter /system.webServer/proxy -name enabled -value True

   #Restart IIS
   - name: Restart IIS
     win_command: powershell.exe -
     args:
       stdin: iisreset.exe /restart