[template]
interval = 2
log-level = "info"
noop = false
sync-only = false
#prefix = "/rproxy"  # etcd directory
src = "proxy.conf.tmpl"
dest = "C:/inetpub/wwwroot/web.config"
owner = "root"
mode = "0666"
keys = [
    "/etcd/uri",
    "/etcd/port",
    "/wmiexporter/uri",
    "/wmiexporter/port",
    "/blackbox/uri",
    "/blackbox/port"
]
reload_cmd = "iisreset.exe /restart"